[package]
name = "aminosim"
version = "0.1.0"
authors = ["Jazpy <jaz.medtre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
rand = "0.7.3"
rayon = "1.5.0"
ndarray = "0.13.1"
